### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by nighttsss** [CalebThePerson/SauceFinder#4]
can you guys make the ipa or smt cuz i dont have mac so i cant do a shit so there any way i can do it?

**Comment by CalebThePerson** [comment]
The Ipa has been created and uploaded.  Pretty sure it works but let me know if it doesn't.  There are few bugs that I am trying to currently fix but let me know if you find anything major, please.  

Also, finding Doujin's via the page is still buggy, and don't be quick to say it isn't working loading times will vary.
