### ISSUE TITLE
search does nothing

### ISSUE THREAD

**Issue by nighttsss** [CalebThePerson/SauceFinder#5]
ik ik you told me to not hurry to say anything but i will keep it there take your time <3
[here](https://streamable.com/05872j)

**Comment by nighttsss** [comment]
also there is way i can donate u?

**Comment by CalebThePerson** [comment]
Yeah, as of right now if the search does nothing that means it sadly couldn't find anything.  I'm trying to work on a way for it to let the users know.  Also I forgot to mention, that it works the best when it isn't cropped in any way, if it is cropped it will have a harder time finding anything .

**Comment by nighttsss** [comment]
You should like do loading thing yk

**Comment by CalebThePerson** [comment]
Yeah, that was the plan and I have it however it just isn't showing.

**Comment by nighttsss** [comment]
stackoverflow ૮₍ ˃ ⤙ ˂ ₎ა

**Comment by CalebThePerson** [comment]
Aight, 99.9% sure I solved this issue with my latest release.  Try it out and lemme know if you find any more problems.
